import React from 'react';
import { Target, Brain, TrendingUp, TrendingDown, BookOpen } from 'lucide-react';
import './AIInsights.css';

const insightsData = [
    {
        id: 1,
        symbol: "TATASTEEL",
        action: "BUY",
        confidence: 88,
        reasoning: "Technical indicators align with strong positive options flow. The recent breakout above ₹145 resistance level is supported by 3x average volume. Sentiment analysis of recent earnings call transcripts shows management is highly optimistic about domestic demand recovery.",
        dataPoints: ["RSI: 62 (Bullish)", "MACD Crossover", "Volume Spike: 320%"]
    },
    {
        id: 2,
        symbol: "WIPRO",
        action: "SELL",
        confidence: 92,
        reasoning: "AI detects a bearish divergence in price action vs RSI. Global macroeconomic news specifically related to European client budget cuts has a high correlation with previous Wipro stock downcycles. Model predicts a 5-8% downside in the next 14 days.",
        dataPoints: ["RSI Bearish Divergence", "Negative News Sentiment", "Target: ₹420"]
    },
    {
        id: 3,
        symbol: "HDFCBANK",
        action: "BUY",
        confidence: 78,
        reasoning: "Deep value territory. The stock is trading at a significant discount to historical PB ratios. Institutional buying pattern detected in the last delivery data. AI models give a high probability of mean reversion over the next 3 months.",
        dataPoints: ["Undervalued (PB: 2.1)", "Institutional Accumulation", "Low IV"]
    }
];

const AIInsights = () => {
    return (
        <>
            <div className="page-header">
                <h1 className="page-title">AI Insights</h1>
                <p style={{ color: 'var(--text-secondary)', marginTop: '8px' }}>
                    Algorithmic stock recommendations based on multi-factor analysis.
                </p>
            </div>

            <div className="ai-insights-grid">
                <div className="recommendations-section">
                    <div className="insights-card glass-panel">
                        <div className="insights-card-header">
                            <div className="insights-icon-wrapper">
                                <Target size={24} />
                            </div>
                            <div className="insights-title-group">
                                <h2>Top Conviction Picks</h2>
                                <p>High-probability trades generated by Kautrix AI</p>
                            </div>
                        </div>

                        <div className="insights-list">
                            {insightsData.map(insight => (
                                <div key={insight.id} className="insight-item">
                                    <div className="insight-item-header">
                                        <div className="stock-id">
                                            <span className="stock-symbol">{insight.symbol}</span>
                                            <span className={`signal-badge ${insight.action.toLowerCase()}`}>
                                                {insight.action}
                                            </span>
                                        </div>
                                        <div className="confidence-score">
                                            <span style={{ fontSize: '0.875rem', color: 'var(--text-secondary)' }}>Confidence</span>
                                            <div className={`score-circle ${insight.confidence > 85 ? 'high' : 'medium'}`}>
                                                {insight.confidence}
                                            </div>
                                        </div>
                                    </div>

                                    <div className="reasoning-box">
                                        <Brain className="reasoning-icon" size={20} />
                                        <div className="reasoning-content">
                                            {insight.reasoning}
                                            <div className="data-points">
                                                {insight.dataPoints.map((dp, i) => (
                                                    <span key={i} className="data-tag">{dp}</span>
                                                ))}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            ))}
                        </div>
                    </div>
                </div>
            </div>
        </>
    );
};

export default AIInsights;
